#
# 8888888b.   .d88888b.  888       888 888b    888 888      .d88888b.        d8888 8888888b.       888888b.    .d88888b. Y88b   d88P 
# 888  "Y88b d88P" "Y88b 888   o   888 8888b   888 888     d88P" "Y88b      d88888 888  "Y88b      888  "88b  d88P" "Y88b Y88b d88P  
# 888    888 888     888 888  d8b  888 88888b  888 888     888     888     d88P888 888    888      888  .88P  888     888  Y88o88P   
# 888    888 888     888 888 d888b 888 888Y88b 888 888     888     888    d88P 888 888    888      8888888K.  888     888   Y888P    
# 888    888 888     888 888d88888b888 888 Y88b888 888     888     888   d88P  888 888    888      888  "Y88b 888     888   d888b    
# 888    888 888     888 88888P Y88888 888  Y88888 888     888     888  d88P   888 888    888      888    888 888     888  d88888b   
# 888  .d88P Y88b. .d88P 8888P   Y8888 888   Y8888 888     Y88b. .d88P d8888888888 888  .d88P      888   d88P Y88b. .d88P d88P Y88b  
# 8888888P"   "Y88888P"  888P     Y888 888    Y888 88888888 "Y88888P" d88P     888 8888888P"       8888888P"   "Y88888P" d88P   Y88b 
#                                                                                                                      
# Author: github.com/kylhuk
# License: GPL-3
#
version: '3.8'

################################################################################
#    ____   _  __ ______   ____   _  __   ____   ____  ____    _  __   ____
#   / __/  | |/_//_  __/  / __/  / |/ /  / __/  /  _/ / __ \  / |/ /  / __/
#  / _/   _>  <   / /    / _/   /    /  _\ \   _/ /  / /_/ / /    /  _\ \  
# /___/  /_/|_|  /_/    /___/  /_/|_/  /___/  /___/  \____/ /_/|_/  /___/  
#
################################################################################
x-stdin-tty: &stdin-tty
  stdin_open: true
  tty: true

x-container-default: &container-default
  <<: *stdin-tty
  networks:
    - custom
  restart: always


##############################################################
#    ____   ____   ___   _   __   ____  _____   ____   ____
#   / __/  / __/  / _ \ | | / /  /  _/ / ___/  / __/  / __/
#  _\ \   / _/   / , _/ | |/ /  _/ /  / /__   / _/   _\ \  
# /___/  /___/  /_/|_|  |___/  /___/  \___/  /___/  /___/  
#
##############################################################
services:
  portainer:
    <<: *container-default
    ports:
        - 8000:8000
        - 9000:9000
    container_name: portainer
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer:/data
    image: portainer/portainer-ce:latest
    environment:
      - TZ=${TZ}

  mqtt:
    <<: *container-default
    ports:
        - 1883:1883
        - 9001:9001
    container_name: mqtt
    volumes:
        - mqtt:/mqtt/config:ro
        - mqtt:/mqtt/data
        - mqtt:/mqtt/log
    image: toke/mosquitto:latest
    environment:
      - TZ=${TZ}

  prometheus:
    <<: *container-default
    ports:
        - 9090:9090
    container_name: prometheus
    volumes:
        - prometheus:/etc/prometheus
        - prometheus:/prometheus
    image: prom/prometheus:latest
    environment:
      - TZ=${TZ}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=50y'

  grafana:
    <<: *container-default
    ports:
      - 3000:3000
    container_name: grafana
    environment:
      - TZ=${TZ}
    volumes:
      - grafana:/var/lib/grafana
      - grafana:/etc/grafana
    image: grafana/grafana:latest

  vpn:
    <<: *stdin-tty
    profiles:
      - donotstart
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    volumes:
      - openvpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic
    networks:
      - vpn
      - custom
    dns: 
      - 172.16.238.1
    environment:
      - TZ=${TZ}

  deluge:
    <<: *container-default
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - DELUGE_LOGLEVEL=warn
    volumes:
      - lama-nas-downloads:/downloads # downloads folder
      - deluge:/config # config files
    ports:
      - 8112:8112

  jackett:
    <<: *container-default
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lama-nas-torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - jackett:/config # config files
    ports:
      - 9117:9117
    
  sonarr:
    <<: *container-default
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarr:/config # config files
      - lama-nas-tvshows:/tv # tv shows folder
      - lama-nas-downloads:/downloads # download folder
    ports:
      - 8989:8989

  radarr:
    <<: *container-default
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - radarr:/config # config files
      - lama-nas-movies:/movies # movies folder
      - lama-nas-downloads:/downloads # download folder
    ports:
      - 7878:7878

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - bazarr:/config # config files
      - lama-nas-movies:/movies # movies folder
      - lama-nas-tvshows:/tv # tv shows folder
    ports:
      - 6767:6767

  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - lama-nas-downloads:/downloads # download folder
      - sabnzbd:/config # config files
    ports:
      - 8080:8080

  nzbhydra2:
    <<: *container-default
    profiles:
      - donotstart
    image: linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    environment:
      - TZ=${TZ}
    volumes:
      - nzbhydra2:/config
      - lama-nas-nzb-blackhole:/nzb-blackhole
      - lama-nas-torrent-blackhole:/torrent-blackhole
    ports:
      - 5076:5076

  emby:
    <<: *container-default
    image: emby/embyserver:latest
    container_name: embyserver
    volumes:
      - emby:/config # Configuration directory
      - emby:/backup
      - lama-nas-movies:/movies # Media directory
      - lama-nas-tvshows:/tv # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      #- /dev/dri/renderD128:/dev/dri/renderD128 # VAAPI/NVDEC/NVENC render nodes
        #- /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
    environment:
      - TZ=${TZ}

  pihole:
    <<: *container-default
    container_name: pihole
    networks:
      - custom
    ports:
      - 192.168.50.102:53:53/tcp
      - 192.168.50.102:53:53/udp
      - 8888:80
    environment:
      - TZ=${TZ}
      - VIRTUAL_HOST=pi.hole
      - PROXY_LOCATION=pi.hole
      - FTLCONF_LOCAL_IPV4=127.0.0.1
      - DNSMASQ_USER=root
      - UID=100000
      - SUID=100000
    volumes:
      - pihole-config:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
      - pihole-unbound:/opt/unbound
    dns:
      - 127.0.0.1
      - 1.1.1.1
    hostname: pi.hole
    image: rlabinc/pihole-unbound:latest 

  clickhouse:
    <<: *container-default
    container_name: clickhouse
    ports:
      - 8123:8123
      - 19000:9000
    environment:
      - TZ=${TZ}
    volumes:
      - clickhouse:/var/lib/clickhouse
      - clickhouse:/var/log/clickhouse-server
      - clickhouse:/etc/clickhouse-server/config.d
      - clickhouse:/etc/clickhouse-server/users.d
      - clickhouse:/docker-entrypoint-initdb.d
    hostname: clickhouse
    image: clickhouse/clickhouse-server:23-alpine

  flaresolverr:
    <<: *container-default
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ={TZ}
    ports:
      - "${PORT:-8191}:8191"

  prowlarr:
    <<: *container-default
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ={TZ}
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
  
  homeassistant:
    <<: *container-default
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ={TZ}
    ports:
      - 8765:8123

  caddy:
    <<: *container-default
    container_name: caddy
    image: wenga/caddy_cloudflare:latest
    cap_add:
      - NET_ADMIN
    environment:
      - TZ={TZ}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_caddyfile:/etc/caddy
      - caddy_site:/srv
      - caddy_data:/data
      - caddy_config:/config
    dns:  
      - 192.168.50.102
  
  homer:
    <<: *container-default
    image: b4bz/homer
    container_name: homer
    volumes:
      - homer:/www/assets
    ports:
      - 16182:8080
    environment:
      - INIT_ASSETS=1 # default
      - TZ={TZ}
  
  openldap:
    <<: *container-default
    image: bitnami/openldap:2
    container_name: openldap
    ports:
      - 389:1389
      - 636:1636
    environment:
      - TZ={TZ}
      - LDAP_ROOT=dc=lama-lan,dc=ch
      - LDAP_ADMIN_DN=cn=admin,dc=lama-lan,dc=ch
    volumes:
      - openldap_data:/bitnami/openldap

  lam:
    <<: *container-default
    image: ghcr.io/ldapaccountmanager/lam:stable
    container_name: lam
    ports:
      - 8800:80
    environment:
      - TZ={TZ}
      - LDAP_DOMAIN=lama-lan.ch
      - LDAP_SERVER=ldap://openldap:1389
      - LDAP_USER=cn=admin,dc=lama-lan,dc=ch
      - LDAP_ORGANISATION="Lama LAN LDAP Account Manager"
    volumes:
      - lam-etc:/etc/ldap-account-manager
      - lam-lib:/var/lib/ldap-account-manager
    depends_on:
      - openldap

  authelia:
    <<: *container-default
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    ports:
      - 9091:9091
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/.JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/.SESSION_SECRET
      # AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /secrets/.STORAGE_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/.STORAGE_ENCRYPTION_KEY
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/.SMTP_PASSWORD
      PUID: 100000
      PGID: 100000
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/.LDAP_PASSWORD
    volumes:
      - authelia-config:/config
      - authelia-secret:/secrets
    depends_on:
      - redis
      - openldap

  redis:
    <<: *container-default
    container_name: redis
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    expose:
     - 6379
  
  ombi:
    <<: *container-default
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - TZ={TZ}
      - BASE_URL=/ombi #optional
    volumes:
      - ombi:/config
    ports:
      - 3579:3579

  lldap:
    <<: *container-default
    image: lldap/lldap:stable
    container_name: lldap
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap-data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      #- UID=####
      #- GID=####
      - TZ={TZ}
      - LLDAP_JWT_SECRET_FILE=/run/secrets/lldap_jwt_secret
      - LLDAP_KEY_FILE=/run/secrets/lldap_key_seed
      - LLDAP_LDAP_BASE_DN=dc=lama-lan,dc=ch
      - LLDAP_LDAP_USER_PASS_FILE=/run/secrets/lldap_user_pass
    
  cadvisor:
    <<: *container-default
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg:ro

  node_exporter:
    <<: *container-default
    image: prom/node-exporter
    container_name: node_exporter

  dockerproxy:
    <<: *container-default
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      VOLUMES: 1
      IMAGES: 1
      TASKS: 1
      SERVICES: 1
    # ports:
    #   - "2375:2375"


######################################################
#    ____   ____  _____   ___    ____ ______   ____
#   / __/  / __/ / ___/  / _ \  / __//_  __/  / __/
#  _\ \   / _/  / /__   / , _/ / _/   / /    _\ \  
# /___/  /___/  \___/  /_/|_| /___/  /_/    /___/  
#
######################################################
secrets:
  lldap_jwt_secret:
    external: true
  lldap_key_seed:
    external: true


######################################################################
#    _  __   ____ ______  _      __  ____    ___    __ __   ____
#   / |/ /  / __//_  __/ | | /| / / / __ \  / _ \  / //_/  / __/
#  /    /  / _/   / /    | |/ |/ / / /_/ / / , _/ / ,<    _\ \  
# /_/|_/  /___/  /_/     |__/|__/  \____/ /_/|_| /_/|_|  /___/  
#
######################################################################
networks:
  custom:
    # use the bridge driver, but enable IPv6
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

  vpn:
    # use the bridge driver, but enable IPv6
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.1


############################################################
#   _   __  ____    __   __  __   __  ___   ____   ____
#  | | / / / __ \  / /  / / / /  /  |/  /  / __/  / __/
#  | |/ / / /_/ / / /__/ /_/ /  / /|_/ /  / _/   _\ \  
#  |___/  \____/ /____/\____/  /_/  /_/  /___/  /___/  
#
############################################################
volumes:
  lama-nas-downloads:
    driver_opts:
      type: "nfs"
      o: "addr=lama-nas.local,nolock,soft,rw"
      device: ":/volume2/downloads"
  
  lama-nas-transcode-cache:
    driver_opts:
      type: "nfs"
      o: "addr=lama-nas.local,nolock,soft,rw"
      device: ":/volume2/downloads/transcode_cache"

  lama-nas-media:
    driver_opts:
      type: "nfs"
      o: "addr=lama-nas.local,nolock,soft,rw"
      device: ":/volume2/media"

  lama-nas-movies:
    driver_opts:
      type: "nfs"
      o: "addr=lama-nas.local,nolock,soft,rw"
      device: ":/volume2/media/movies"

  lama-nas-tvshows:
    driver_opts:
      type: "nfs"
      o: "addr=lama-nas.local,nolock,soft,rw"
      device: ":/volume2/media/tvshows"
  
  lama-nas-torrent-blackhole:
    driver_opts:
      type: "nfs"
      o: "addr=lama-nas.local,nolock,soft,rw"
      device: ":/volume2/downloads/torrent-blackhole"
      
  
  lama-nas-nzb-blackhole:
    driver_opts:
      type: "nfs"
      o: "addr=lama-nas.local,nolock,soft,rw"
      device: ":/volume2/downloads/nzb-blackhole"
  
  sonarr:
  radarr:
  tdarr:
  portainer:
  mqtt:
  prometheus:
  grafana:
  openvpn:
  clickhouse:
  emby:
  deluge:
  pihole-config:
  pihole-dnsmasq:
  nzbhydra2:
  sabnzbd:
  bazarr:
  jackett:
  prowlarr:
  homeassistant:
  pihole-unbound:
  netdataconfig:
  netdatalib:
  netdatacache:
  caddy_caddyfile:
  caddy_site:
  caddy_data:
  caddy_config:
  homer:
  openldap_data:
  lam-etc:
  lam-lib:
  authelia-config:
  authelia-secret:
  ombi:
  lldap-data: